# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x86\x01\n\x04Task\x12\r\n\x05Place\x18\x01 \x01(\t\x12\x0c\n\x04\x46ood\x18\x02 \x01(\t\x12\x11\n\tInterests\x18\x03 \x01(\t\x12\x0e\n\x06Health\x18\x04 \x01(\t\x12\x0c\n\x04\x44\x61ys\x18\x05 \x01(\x05\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x0f\n\x07in_date\x18\x07 \x01(\t\x12\x10\n\x08out_date\x18\x08 \x01(\t\"\x18\n\x07GetTask\x12\r\n\x05\x65mail\x18\x01 \x01(\t\" \n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"/\n\x15\x43hatHistoriesResponse\x12\x16\n\x0e\x63hat_histories\x18\x01 \x03(\t2`\n\x04\x43hat\x12&\n\x0e\x66inal_endpoint\x12\x05.Task\x1a\r.ChatResponse\x12\x30\n\x0cget_endpoint\x12\x08.GetTask\x1a\x16.ChatHistoriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=15
  _globals['_TASK']._serialized_end=149
  _globals['_GETTASK']._serialized_start=151
  _globals['_GETTASK']._serialized_end=175
  _globals['_CHATRESPONSE']._serialized_start=177
  _globals['_CHATRESPONSE']._serialized_end=209
  _globals['_CHATHISTORIESRESPONSE']._serialized_start=211
  _globals['_CHATHISTORIESRESPONSE']._serialized_end=258
  _globals['_CHAT']._serialized_start=260
  _globals['_CHAT']._serialized_end=356
# @@protoc_insertion_point(module_scope)
