# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.final_endpoint = channel.unary_unary(
                '/Chat/final_endpoint',
                request_serializer=chat__pb2.Task.SerializeToString,
                response_deserializer=chat__pb2.ChatResponse.FromString,
                )
        self.get_endpoint = channel.unary_unary(
                '/Chat/get_endpoint',
                request_serializer=chat__pb2.GetTask.SerializeToString,
                response_deserializer=chat__pb2.ChatHistoriesResponse.FromString,
                )


class ChatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def final_endpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_endpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'final_endpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.final_endpoint,
                    request_deserializer=chat__pb2.Task.FromString,
                    response_serializer=chat__pb2.ChatResponse.SerializeToString,
            ),
            'get_endpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.get_endpoint,
                    request_deserializer=chat__pb2.GetTask.FromString,
                    response_serializer=chat__pb2.ChatHistoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def final_endpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/final_endpoint',
            chat__pb2.Task.SerializeToString,
            chat__pb2.ChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_endpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Chat/get_endpoint',
            chat__pb2.GetTask.SerializeToString,
            chat__pb2.ChatHistoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
